project/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
app_name= 'core'
urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('panel/', include('panel.urls'),name='panel'),
    path('sparcels/',include('sous_parcel.urls'),name='sous'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email', 'password1', 'password2']

project/core/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login 
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import SignUpForm
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: not u.is_authenticated, login_url='panel:frontpage')
def frontpage(request):
    return render(request, 'core/frontpage.html')
@user_passes_test(lambda u: not u.is_authenticated, login_url='panel:frontpage')
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            pr = request.user.id
            if(User.objects.filter(pk=pr).count()>0):
                user=request.user
                user.first_name =form.cleaned_data["first_name"]
                user.last_name =form.cleaned_data["last_name"]
                user.email =form.cleaned_data["email"]
                user.username =form.cleaned_data["username"]
                user.save()
            else :
                user = form.save()

                login(request, user)

            return redirect('panel:frontpage')
    else:
        form = SignUpForm()
    
    return render(request, 'core/signup.html', {'form': form})

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/logo.png'%}">
<link rel="icon" type="image/png" href="{% static 'img/logo.png'%}">
<title>
  
    {% block title %}{% endblock %}

</title>
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
<!-- Nucleo Icons -->
<link href="{% static 'css/nucleo-icons.css'%}" rel="stylesheet" />
<link href="{% static 'css/nucleo-svg.css'%}" rel="stylesheet" />
<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="{% static 'css/nucleo-svg.css'%}" rel="stylesheet" />
<!-- CSS Files -->

<link id="pagestyle" href="{% static 'css/soft-ui-dashboard.css'%}?v=1.0.7" rel="stylesheet" />
</head>
    <body class="bg-teal-600">                
                    <div class="container position-sticky z-index-sticky top-0">
                        <div class="row">
                          <div class="col-12">
                            <!-- Navbar -->
                            <nav class  ="navbar navbar-expand-lg blur blur-rounded top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
                              <div class="container-fluid pe-0">
                                <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="../pages/dashboard.html">
                                  Agre-IOT-DZ
                                </a>
                                <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                                  <span class="navbar-toggler-icon mt-2">
                                    <span class="navbar-toggler-bar bar1"></span>
                                    <span class="navbar-toggler-bar bar2"></span>
                                    <span class="navbar-toggler-bar bar3"></span>
                                  </span>
                                </button>
                                <div class="collapse navbar-collapse" id="navigation">
                                  <ul class="navbar-nav mx-auto ms-xl-auto me-xl-7">
                                    <li class="nav-item">
                                      <a class="nav-link me-2" href=" {% url 'core:frontpage' %} ">
                                        <i class="fa fa-home opacity-6 text-dark me-1"></i>
                                        ACCUEIL
                                      </a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link me-2" href="/signup/">
                                        <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                                        S'enregistrer
                                      </a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link me-2" href="/login/">
                                        <i class="fas fa-key opacity-6 text-dark me-1"></i>
                                        connectez-vous
                                      </a>
                                    </li>
                                  </ul>

                                </div>
                              </div>
                            </nav>
                            <!-- End Navbar -->
                          </div>
                        </div>
                      </div>
        

{% block content %}

{% endblock %}
        
    </main>

{% block front %}

{% endblock %}
<footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">

          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            à propos
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Équipe
          </a>

        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fas fa-envelope"></span>
          </a>

          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-facebook"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-telegram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            Copyright © <script>
              document.write(new Date().getFullYear())
            </script> by M.M.A.D
          </p>
        </div>
      </div>
    </div>
  </footer>
        {% block scripts %}
        {% endblock %}
        <script src="{% static 'js/core/popper.min.js'%}"></script>
        <script src="{% static 'js/core/bootstrap.min.js'%}"></script>
        <script src="{% static 'js/plugins/perfect-scrollbar.min.js'%}"></script>
        <script src="{% static 'js/plugins/smooth-scrollbar.min.js'%}"></script>
        <script>
          var win = navigator.platform.indexOf('Win') > -1;
          if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
              damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
          }
        </script>
        <!-- Github buttons -->
        <script async defer src="https://buttons.github.io/buttons.js"></script>
        <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="{% static 'js/soft-ui-dashboard.min.js'%}?v=1.0.7"></script>
    </body>
</html>

project/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Log in | {% endblock %}

{% block content %}

<main class="main-content  mt-0">
    <section>

        <div class="page-header min-vh-75">
        <div class="container">
            <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
                <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                    <h3 class="font-weight-bolder text-info text-gradient">Content de te revoir</h3>
                    <p class="mb-0">Entrez votre nom d'utilisateur et votre mot de passe pour vous connecter</p>
                </div>
                <div class="card-body">
                    <form role="form" method="post" action=".">
                        {% csrf_token %}
                    <label>Nom d'utilisateur</label>
                    <div class="mb-3">
                        <input type="text" name="username" class="form-control" placeholder="nom d'utilisateur" aria-label="username" >
                    </div>
                    <label>Mot de passe</label>
                    <div class="mb-3">
                        <input type="password" name="password" class="form-control" placeholder="Mot de passe" aria-label="Password" aria-describedby="password-addon">
                    </div>
                  
                    {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %} 
                            <div class="mb-5 p-4 rounded-xl bg-danger text-white">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                    <div class="text-center">
                        <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">connectez-vous</button>
                    </div>
                    
                    </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                    <p class="mb-4 text-sm mx-auto">
                        Vous n'avez pas de compte ?
                    <a href="javascript:;" class="text-info text-gradient font-weight-bold">S'enregistrer</a>
                    </p>
                </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static 'img/loginbg.png'%}')"></div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>

</main>

{% endblock %}

project/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Sign up | {% endblock %}

{% block content %}
<section class="min-vh-100 mb-8 ">
    <div class="page-header align-items-start min-vh-50 pt-5 pb-11 m-3 border-radius-lg" style="background-image: url('{% static 'img/signupbg.jpg'%}');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5 text-center mx-auto">
            <h1 class="text-white mb-2 mt-5">Bienvenue!</h1>
            <p class="text-lead text-white"></p>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-lg-n10 mt-md-n11 mt-n10">
        <div class="col-xl-4 col-lg-5 col-md-7 ms-auto">
          <div class="card z-index-0 bg-light">
           
            <div class="card-body">
              <div class="mb-3">
                <input type="text" name="agriculteur cart ID" class="form-control" placeholder="agriculteur cart ID" aria-label="agriculteur cart ID" aria-describedby="agriculteur cart ID">
              </div>
              <form method="post" action="." role="form text-left">
                {% csrf_token %}
                
                <div class="mb-3">
                  <input type="text" name="first_name" class="form-control" placeholder="Nom" aria-label="first_name" aria-describedby="first_name">
                </div>
                <div class="mb-3">
                  <input type="text" name="last_name" class="form-control" placeholder="Prenom" aria-label="last_name" aria-describedby="last_name">
                </div>
                <div class="mb-3">
                  <input type="text" name="email" class="form-control" placeholder="email" aria-label="email" aria-describedby="email">
                </div>
                <div class="mb-3">
                  <input type="text" name="username" class="form-control" placeholder="Nom d'utilisateur" aria-label="Nom d'utilisateur" aria-describedby="email-addon">
                </div>
                <div class="mb-3">
                  <input type="password" name="password1" class="form-control" placeholder="Mot de passe" aria-label="Nom d'utilisateur" aria-describedby="password-addon">
                </div>
                <div class="mb-3">
                    <input type="password" name="password2" class="form-control" placeholder="Repeter Mot de passe" aria-label="Nom d'utilisateur" aria-describedby="password-addon">
                  </div>
                  
            
                <div class="text-center">
                  <button type="submit" Name="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Sign up</button>
                </div>
               
        
                <p class="text-sm mt-3 mb-0">Already have an account?<a href="/login/" class="text-dark font-weight-bolder">Sign in</a></p>
              </form>
            </div>
           
        </div>
        
      </div>
      <div class="col-xl-4 col-lg-5 col-md-7 ">

        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endif %}
    </div>
    </div>
  </section>



{% endblock %}