project/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
app_name= 'core'
urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

project/panel/urls.py
from django.urls import path

from . import views
app_name = "panel"
urlpatterns = [
path('', views.frontpage, name='frontpage'),
path('parcels/',views.parcels,name='parcels'),
path('creatparcel/',views.cree_parcel,name='cree_parcel'),
path('creatprofile/',views.cree_profile,name='cree_profile'),
path('notifications/',views.notifications,name='notifications'),
path('creatsparcel/',views.cree_s_parcel,name='cree_sparcel'),
path('profile/',views.profile,name='profile'),
path('tables/',views.tables,name='tables')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('panel/', include('panel.urls'),name='panel'),
    path('sparcels/',include('sous_parcel.urls'),name='sous'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/sous_parcel/urls.py
from django.urls import path,re_path
from . import views
app_name = 'sous_parcel'
urlpatterns = [
    path('<int:id>/',views.S_parcel,name='sparcels'),
    path('sparcel/<int:id>/',views.sparcel,name='sparcel'),
    re_path('(?P<id>[\w-]+)/capters',views.capters,name='capters'),
    path('capter/run',views.run_capter,name='runcapter'),
    path('capters/valeurs',views.capters_values,name='capter_value'),
    path('creatcapter/<int:sparcelid>/',views.cree_capter,name='cree_capter'),
]

project/panel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
class parcel(models.Model):
    
    name = models.CharField(max_length=255)
    details= models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.JSONField()
    def __str__(self):
        return self.name

class notification(models.Model):
    
    contenu = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    onclick=models.BigIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class Profile(models.Model):   
    mobile =models.CharField(max_length=10,null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    agrecardid = models.CharField(max_length=500,null=True)
    image = models.ImageField(null=True,blank=True)  
   
   

project/panel/forms.py
from django.forms import ModelForm
from .models import parcel ,Profile
from sous_parcel.models import sous_parcel
class CreeParcelForm(ModelForm):
    class Meta:
        model = parcel
        fields = ['name','details','location']
class CreeProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['mobile','agrecardid','image']
class creeSparceleForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(creeSparceleForm, self).__init__(*args, **kwargs)
        self.fields['parcel'].queryset = parcel.objects.filter(user=user)
    class Meta:
        model = sous_parcel
        fields = '__all__'

project/panel/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from .models import parcel,notification,Profile
from sous_parcel.models import sous_parcel ,capteur
from .forms import CreeParcelForm ,CreeProfileForm,creeSparceleForm
from django.http import JsonResponse
import json
def tables(request):
    current_user=request.user.id
    parcels =parcel.objects.filter(user_id=current_user)
    sparcels =sous_parcel.objects.filter(parcel__in=parcels)
    capters =capteur.objects.filter(sous_parcel__in=sparcels)
    first_parcel =parcels.first()
    context ={'capters': capters,'sparcels':sparcels,'parcels':parcels,'first':first_parcel}
    return render(request,'panel/tables.html',context)
def frontpage(request):
    current_user=request.user.id
    parcels =parcel.objects.filter(user_id=current_user)
    return render(request, 'panel/frontpage.html',{'parcels':parcels})

@login_required
def parcels(request):
    context =userinfo(request)
    return render(request,'panel/parcels.html',context)
@login_required
def userinfo(request):
    current_user=request.user.id
    parcels =parcel.objects.filter(user_id=current_user)
    sparcels =sous_parcel.objects.filter(parcel__in=parcels)
    sous_parcels=sparcels.count()
    capters =capteur.objects.filter(sous_parcel__in=sparcels).count()
    first_parcel =parcels.first()
    context ={'capters': capters,'sparcels':sous_parcels,'parcels':parcels,'first':first_parcel}
    return context

def profile(request):
    pr = request.user.id
    if(Profile.objects.filter(user=pr).count()>0):
        profil = request.user.profile
        return render(request,'panel/profile.html',{'user': request.user,'profile':profil})
    else : 
        return redirect('panel:cree_profile')

@login_required
@method_decorator(csrf_exempt, name='dispatch')
def cree_parcel(request):
    if request.method == 'POST':
        form = CreeParcelForm(request.POST)
        if form.is_valid():
            new_parcel = parcel(
                        user = request.user,
                        details = form.cleaned_data["details"],
                        name = form.cleaned_data["name"],
                        location = form.cleaned_data["location"],
                    )
            new_parcel.save()
            context = {'status': 'success'}
            return redirect("panel:parcels")

        else:  return JsonResponse({'status': 'failed'})
    else : 
        form = CreeParcelForm()
    return render(request,'panel/newparcel.html',{'form':form})

@login_required
@method_decorator(csrf_exempt, name='dispatch')
def cree_profile(request):
    
    if request.method == 'POST':
       
        form = CreeProfileForm(request.POST, request.FILES)
        if form.is_valid():
            pr = request.user.id
            if(Profile.objects.filter(user=pr).count()>0):
                profile= request.user.profile
                profile.mobile =form.cleaned_data["mobile"]
                profile.agrecardid = form.cleaned_data["agrecardid"]
                profile.image =  form.cleaned_data["image"]
            
            else:
                profile =  Profile(
                        mobile =form.cleaned_data["mobile"],
                        user = request.user,
                        agrecardid = form.cleaned_data["agrecardid"],
                        image =  form.cleaned_data["image"],
                        
                )
            profile.save()
            context = {'status': 'success'}
            return redirect("panel:profile")
        else:  return JsonResponse({'status': 'failed'})
    else :
        form = CreeProfileForm()
    return render(request,'panel/creeprofile.html',{'form':form})

@login_required
@method_decorator(csrf_exempt, name='dispatch')
def notifications(request):
        valeurs = []
        valeur = notification.objects.filter(user=request.user.id).values().order_by('-id')[:4]
        val = list(valeur)
        valeurs += val
        return JsonResponse({'valeurs': valeurs})
@login_required
@method_decorator(csrf_exempt, name='dispatch')
def cree_s_parcel(request):
    if request.method == 'POST':
        form = creeSparceleForm(request.user,request.POST)

        if form.is_valid():
           
            form.save()
            return redirect("panel:tables")
        else:  return JsonResponse({'status': 'failed'})
    else:
        form = creeSparceleForm(request.user)
    
    return render(request, 'panel/newsparcel.html', {'form': form})

project/panel/templates/panel/parcels.html
{% extends 'panel/base.html' %}

{% block title %}Welcome | {% endblock %}
{% block activelnk2 %}active{% endblock activelnk2 %}
{% block paneltitle %}Parcels{% endblock paneltitle %}

{% block content %}


<div class="container-fluid py-4">
  <div class="row">
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Les Capters</p>
                <h5 class="font-weight-bolder mb-0">
                  {{capters}}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fas fa-temperature-low"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Les sous-parcels</p>
                <h5 class="font-weight-bolder mb-0">
                  {{sparcels}}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
               
                <i  class="fas fa-seedling" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Les Parcels</p>
                <h5 class="font-weight-bolder mb-0">
                  {{parcels|length}}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fas fa-tree"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">La Dernière parcel</p>
                <h5 class="font-weight-bolder mb-0">
                  {{first.name}}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fas fa-tree"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="row mt-4">
   

        <div class="col-md">     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="" />

            <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
            
            <div id="map"></div></div>
        <div class="col ">
            <div class="row">
                <div class="col">
                  <div class="card">
                    <div class="card-header pb-0">
                      <div class="row">
                        <div class="col-lg-6 col-7">
                          <h6>Projects</h6>
                          <p class="text-sm mb-0">
                            <i class="fa fa-check text-info" aria-hidden="true"></i>
                            <span class="font-weight-bold ms-1">{{parcels|length }} parcels</span> click pour affiche en cart
                          </p>
                          <a href=" {% url 'panel:cree_parcel' %}"><span class="badge badge-sm bg-gradient-success">ajouter parcel</span></a>
                        </div>
                        
                      </div>
                    </div>
                    <div class="card-body px-0 pb-2">
                      <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                          <thead>
                            <tr>
                              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom</th>
                              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Details</th>
                              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"></th>
                              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"></th>
                            </tr>
                          </thead>
                          <tbody>
                          
                            {%for parcel in parcels%}
                                
                            <tr>
                              <td>
                                <div class="d-flex px-2 py-1">
                                  <div class="d-flex flex-column justify-content-center">
                                    <h6 class="mb-0 text-sm"  >{{parcel.name}}</h6>
                                  </div>
                                </div>
                              </td>
                              <td class="align-middle text-center text-sm">
                                <span class="text-xs font-weight-bold"> {{parcel.details}} </span>
                              </td>
                              <td class="align-middle text-center text-sm">
                                
                                <button type="button" class="btn btn-success" onclick="parcelposition({{parcel.location.1}})"><i class="fas fa-map-marker-alt"></i> <span class="ms-2"> position</span></button>
                              </td>
                              
                              <td class="align-middle text-center text-sm">
                                <a href="{% url 'sous_parcel:sparcels' parcel.id %}" class="btn btn-success"><span class="text-xs font-weight-bold"> afficher sous_parcels </span></a>
                              </td>
                            </tr>
                            {% endfor %}
                         </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
            </div>

        </div>




     
        
    </div>
</div>
<!-- prettier-ignore -->

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
<script>
  // All the code for the leaflet map will come here
const map = L.map('map').setView([35.698894, -0.650763], 14);
const basemaps = {
    StreetView: L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',   {attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}),
    Topography: L.tileLayer.wms('http://ows.mundialis.de/services/service?',   {layers: 'TOPO-WMS'}),
    Places: L.tileLayer.wms('http://ows.mundialis.de/services/service?', {layers: 'OSM-Overlay-WMS'})
  };
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' }).addTo(map);

  L.control.layers(basemaps).addTo(map);
  basemaps.StreetView.addTo(map);
  var popup = L.popup();

function onMapClick(e) {
    popup
        .setLatLng(e.latlng)
        .setContent("You clicked the map at " + e.latlng.toString())
        .openOn(map);
}

map.on('click', onMapClick);

function parcelposition(loc){

  map.panTo(new L.LatLng(loc.lat, loc.long));
}

</script>
{%for parcel in parcels %}
    
<script>
  var loc = {{parcel.location|safe}};
  console.log(loc);

var locationArray = [];

for (let key in loc) {
  const lat = parseFloat(loc[key].lat);
  const long = parseFloat(loc[key].long);
  locationArray.push([lat, long]);
}
  var polygon = L.polygon([
    locationArray
   
]).addTo(map);

</script>
{% endfor %}

{% endblock %}

project/panel/templates/panel/profile.html
{% extends 'panel/base.html' %} 
{% load static %}


{% block title %}Welcome | {% endblock %}
{% block activelnk5 %}active{% endblock activelnk5 %}
{% block paneltitle %}Profile{% endblock paneltitle %}

{% block content %}


<div class="container-fluid">
    <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('../../img/vr-bg.jpg'); background-position-y: 50%;">
      <span class="mask bg-gradient-primary opacity-6"></span>
    </div>
    <div class="card card-body blur shadow-blur mx-4 mt-n6 overflow-hidden">
      <div class="row gx-4">
        <div class="col-auto">
          <div class="avatar avatar-xxl position-relative">
            <img  src="../../img/{{profile.image}}"  alt="profile_image" class="w-100 border-radius-lg shadow-sm">
          </div>
          
        </div>
        <div class="  col-12 col-xl-4">
          <div class="card h-100">
            <div class="card-header pb-0 p-3">
              <div class="row">

          <ul class="list-group">
            <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Nom et prénom:</strong> &nbsp; {{user.first_name}} {{user.last_name}}</li>
            <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Agreculteur card id:</strong> &nbsp; {{profile.agrecardid}}</li>
            <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Mobile:</strong> &nbsp;  {{profile.mobile}} </li>
            <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Email:</strong> &nbsp; {{user.email}} </li>
            
          </ul>
        </div>
       
      
      </div>
      
    </div>
    
  </div>
        

      </div>
    </div>
  </div>
  <div class="container-fluid row py-4">
    
    <div class="  col-6">
      <div class="card h-100">
        <div class="card-header pb-0 p-3">
              <form method="post" action=" {% url 'panel:cree_profile' %} " role="form text-left" enctype="multipart/form-data" >
                  {% csrf_token %}
                  <div class="mb-3">
                      <input type="number" name="mobile" class="form-control" id="form-name" placeholder="Mobile" aria-label="Mobile" >
                    </div>
                    <div class="mb-3">
                      <input type="number" name="agrecardid" class="form-control" id="form-name" placeholder="agreculteur card id" aria-label="agrecardid" >
                    </div>
                    <div class="mb-3">
                      <input type="file" name="image" class="form-control" id="form-name" placeholder="image" aria-label="image" >
                    </div>
                  <div class="text-center">
                      <button type="submit" Name="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Submit</button>
                  </div>
              </form>
        </div>
      </div>
    </div>

    <div class="  col">
      <div class="card h-100">
        <div class="card-header pb-0 p-3">
      <form method="post" action=" {% url 'core:signup' %} " role="form text-left">
        {% csrf_token %}
        
        <div class="mb-3">
          <input type="text" name="first_name" class="form-control" placeholder="Nom" aria-label="first_name" aria-describedby="first_name">
        </div>
        <div class="mb-3">
          <input type="text" name="last_name" class="form-control" placeholder="Prenom" aria-label="last_name" aria-describedby="last_name">
        </div>
        <div class="mb-3">
          <input type="text" name="email" class="form-control" placeholder="email" aria-label="email" aria-describedby="email">
        </div>
        <div class="mb-3">
          <input type="text" name="username" class="form-control" placeholder="Nom d'utilisateur" aria-label="Nom d'utilisateur" aria-describedby="email-addon">
        </div>
       
    
        <div class="text-center">
          <button type="submit" Name="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Submit</button>
        </div>
       

      </form>
    </div>
   
</div>

</div>
  </div>
</div>

{% endblock %}

project/panel/templates/panel/tables.html
{% extends 'panel/base.html' %}
{% load static %}
{% block activelnk3 %}active{% endblock activelnk3 %}
{% block paneltitle %}Tableu{% endblock paneltitle %}
{% block content %}
<div class="container-fluid py-4">
  <div class="row">
    <div class="col">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="row">
            <div class="col-lg-10 col-md">
              <h6>Sous_parcel table</h6>
            </div>
            <div class="col-lg-2 col-md me-3">
              <a href=" {% url 'panel:cree_sparcel' %}"><span class="badge badge-sm bg-gradient-success">add sous_parcel</span></a>
            </div>
          </div>
       </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0 row">
            <table class="table align-items-center mb-0 ">
              <thead>
                <tr>
                  <th
                    class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                  >
                    Nom
                  </th>
                  <th
                    class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"
                  >
                    Details
                  </th>
                  <th
                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                  >
                   
                  </th>
                  <th
                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                  >
                    Parcel
                  </th>
                  <th class="text-secondary opacity-7"></th>
                </tr>
              </thead>
              <tbody>
                {% for sparcel in sparcels %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                      
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{sparcel.name}}</h6>
                        <p class="text-xs text-secondary mb-0">
                          {{sparcel.id}}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">
                      {{sparcel.details}}
                    </p>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <a href=" {% url 'sous_parcel:sparcel' sparcel.id %} "
                      ><span class="badge badge-sm bg-gradient-success"
                        >affiche</span
                      ></a
                    >
                  </td>
                  <td class="align-middle text-center">
                    <span class="text-secondary text-xs font-weight-bold"
                      > {{sparcel.parcel}} </span
                    >
                  </td>
                  
                </tr>
                {% endfor %}
              </tbody>
            </table>
           
          </div>
        </div>
      </div>
    </div>
    <div class="col">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-10 col-md">
                <h6>Parcels table</h6>
              </div>
              <div class="col-lg-2 col-md me-3">
                <a href=" {% url 'panel:cree_parcel' %}"><span class="badge badge-sm bg-gradient-success">add parcel</span></a>
              </div>
            </div>
         </div>
          <div class="card-body px-0 pt-0 pb-2">
            <div class="table-responsive p-0 row">
              <table class="table align-items-center mb-0 ">
                <thead>
                  <tr>
                    <th
                      class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      Name
                    </th>
                    <th
                      class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"
                    >
                      Details
                    </th>
                    <th
                      class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      0
                    </th>
                    <th
                      class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      
                    </th>
                    <th class="text-secondary opacity-7"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for sparcel in parcels %}
                  <tr>
                    <td>
                      <div class="d-flex px-2 py-1">
                        
                        <div class="d-flex flex-column justify-content-center">
                          <h6 class="mb-0 text-sm">{{sparcel.name}}</h6>
                          <p class="text-xs text-secondary mb-0">
                            {{sparcel.id}}
                          </p>
                        </div>
                      </div>
                    </td>
                    <td>
                      <p class="text-xs font-weight-bold mb-0">
                        {{sparcel.details}}
                      </p>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <a href=" {% url 'sous_parcel:sparcel' sparcel.id %} "
                        ><span class="badge badge-sm bg-gradient-success"
                          >affiche</span
                        ></a
                      >
                    </td>
                    <td class="align-middle text-center">
                      <span class="text-secondary text-xs font-weight-bold"
                        >23/04/18</span
                      >
                    </td>
                    <td class="align-middle">
                      <a
                        href="javascript:;"
                        class="text-secondary font-weight-bold text-xs"
                        data-toggle="tooltip"
                        data-original-title="Edit user"
                      >
                        Edit
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             
            </div>
          </div>
        </div>
      </div>
    <div class="col">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <div class="row">
              <div class="col-lg-10 col-md">
                <h6>Capteurs table</h6>
              </div>
              <div class="col-lg-2 col-md me-3">
              </div>
            </div>
         </div>
          <div class="card-body px-0 pt-0 pb-2">
            <div class="table-responsive p-0 row">
              <table class="table align-items-center mb-0 ">
                <thead>
                  <tr>
                    <th
                      class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      Name
                    </th>
                    <th
                      class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"
                    >
                      details
                    </th>
                    <th
                      class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      
                    </th>
                    <th
                      class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                    >
                      sous_parcel
                    </th>
                    <th class="text-secondary opacity-7"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for sparcel in capters %}
                  <tr>
                    <td>
                      <div class="d-flex px-2 py-1">
                        <div>
                          <img
                            src="{% static 'img/small-logos/'|add:sparcel.img|add:'' %}"
                            class="avatar avatar-sm me-3"
                            alt="user1"
                          />
                        </div>
                        <div class="d-flex flex-column justify-content-center">
                          <h6 class="mb-0 text-sm">{{sparcel.name}}</h6>
                          <p class="text-xs text-secondary mb-0">
                            {{sparcel.id}}
                          </p>
                        </div>
                      </div>
                    </td>
                    <td>
                      <p class="text-xs font-weight-bold mb-0">
                        {{sparcel.details}}
                      </p>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <a href=" {% url 'sous_parcel:sparcel' sparcel.id %} "
                        ><span class="badge badge-sm bg-gradient-success"
                          >affiche</span
                        ></a
                      >
                    </td>
                    <td class="align-middle text-center">
                      <span class="text-secondary text-xs font-weight-bold"
                        > {{sparcel.sous_parcel}} </span
                      >
                    </td>
                    
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             
            </div>
          </div>
        </div>
      </div>
  </div>
  
</div>
<!-- prettier-ignore -->
{% endblock %}